controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_events_show:
    path: '/events/{id}'
    controller: 'App\Controller\EventsController::show'